### ISSUE TITLE
Crashes when a transition contains a CSS variable

### ISSUE THREAD

**Issue by ivan-aksamentov** [kristerkari/stylelint-high-performance-animation#6]
### The problem
The plugin crashes on the following CSS fragment:

```css
:root {
  --sidebar-transition: all 0.3s ease;
}

.example {
  transition: var(--sidebar-transition);
}
```

with the following error:
```
TypeError: Cannot read property 'index' of undefined
    at crash.css:6:3
    at cssRoot.walkDecls.decl (node_modules/stylelint-high-performance-animation/index.js:192:59)
    at node_modules/postcss/lib/container.js:205:16
    at node_modules/postcss/lib/container.js:135:18
    at Rule.each (node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (node_modules/postcss/lib/container.js:131:17)
    at node_modules/postcss/lib/container.js:148:24
    at Root.each (node_modules/postcss/lib/container.js:101:16)
    at Root.walk (node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (node_modules/postcss/lib/container.js:203:17)
    at node_modules/stylelint-high-performance-animation/index.js:164:13

```
### Versions
package | version
-------|--------
node | 11.15.0
yarn | 1.15.2
stylelint | 10.0.1
stylelint-high-performance-animation | 1.2.0

### How to reproduce
```bash
git clone https://github.com/ivan-aksamentov/repro-stylelint-hpa-crash
cd repro-stylelint-hpa-crash
yarn install
stylelint crash.css


```

### Relevant code
https://github.com/kristerkari/stylelint-high-performance-animation/blob/a515986fa8424c61049f693b50d88a706e42963b/index.js#L186-L195

**Comment by kristerkari** [comment]
Thanks @ivan-aksamentov, I'll have a look.

**Comment by kristerkari** [comment]
fix released in v1.2.1:
https://github.com/kristerkari/stylelint-high-performance-animation/releases/tag/1.2.1

**Comment by SharakPL** [comment]
@kristerkari I still get this error every time I type `transition: ` in my .scss file. 

> TypeError: Cannot read property 'index' of undefined at ...

https://github.com/kristerkari/stylelint-high-performance-animation/blob/3997b9943e5c4c95475d2df3f204fd9ce68791cf/index.js#L192

I use v.1.5.0

**Comment by kristerkari** [comment]
Thanks @SharakPL, I'll have a look

**Comment by kristerkari** [comment]
@SharakPL Thanks, the bug is fixed in v1.5.1

I knew that there was some error thrown, but I could not make a fix earlier because I did not know how to trigger it.

**Comment by SharakPL** [comment]
Thanks :)
